package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class PPal extends javax.swing.JPanel {

    VPal v;
    public PPal(VPal v) {
        this.v = v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conecta4Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonJugar = new javax.swing.JButton();
        botonReglas = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 1));

        conecta4Label.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        conecta4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conecta4Label.setText("CONECTA 4");
        add(conecta4Label);
        add(jPanel1);

        panelBotones.setLayout(new java.awt.GridLayout(1, 3));

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });
        panelBotones.add(botonJugar);

        botonReglas.setText("Reglas");
        botonReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReglasActionPerformed(evt);
            }
        });
        panelBotones.add(botonReglas);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        panelBotones.add(botonSalir);

        add(panelBotones);
    }// </editor-fold>//GEN-END:initComponents

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        v.setContentPane(v.pJuego);
        //IMPORTANTE EL REVALIDATE QUE SI NO NO SE CAMBIA EL PANEL ***************************************************
        v.revalidate();
    }//GEN-LAST:event_botonJugarActionPerformed

    private void botonReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReglasActionPerformed
        JOptionPane.showMessageDialog(null, "Conecta 4, no tiene mucho misterio.");
        JOptionPane.showMessageDialog(null, "Es broma, pulsa cualquiera de las columnas para introducir una ficha. El primero que meta 4 seguidas gana.");
    }//GEN-LAST:event_botonReglasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        //dispose hace que se cierre la ventana, asi que cierra la app
        JOptionPane.showMessageDialog(null, "Hasta la proxima");
        v.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonReglas;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel conecta4Label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
