package GUI;

import data.Juego;
import javax.swing.JPanel;

/**
 *
 * @author alber
 */
public class VPal extends javax.swing.JFrame {
    
    public Juego juego;
    JPanel ppal,pJuego;
    final String NOM;
    
    public VPal(String nom, Juego juego) {
        this.juego = juego;
        this.NOM=nom;
        this.setTitle(NOM);
        ppal = new PPal(this);
        //le paso el juego al panel del juego para que pueda usarlo
        pJuego = new PJuego(this, juego);
        initComponents();
        this.setSize(800,600);
        this.setLocationRelativeTo(null);
        this.setContentPane(ppal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
